messenger4j:
  appSecret: 6a17b6f4d5f2d1f98d9ac4ea3decb31c
  verifyToken: AB
  pageAccessToken: EAAaISLtfMnUBAPZBulH0DXZAoNkhpd0FNa7Scp2reaQrbQJXMBJixjoZCGMOsW7rgt44w2CGcRFlc0NRvZBh8YiyqStuaJaQe96RZBEozkt1JE6dP4einPNzVbMdS8BC92FzYrvZA7M7B4JUsHbNczorwCw0tnTSeSqT8HAOGZAnQZDZD
logging:
  level:
    com:
      github:
        messenger4j: INFO

